--[[--
The spell lists of the System Reference Documents (SRD 5.1 for the 2014
rules, SRD 5.2.1 for the 2024 rules), in spells/<edition>_<language>.lua.

The files are generated by tools/srd/build.py. Only one list is kept in
memory at a time: it is loaded when first needed.
--]]

local I18n = require("dnd5e_i18n")
local lfs = require("libs/libkoreader-lfs")
local util = require("util")
local T = I18n.T

local Spells = {}

local plugin_dir = (debug.getinfo(1, "S").source:match("^@(.*/)") or "./")
local spells_dir = plugin_dir .. "spells/"

-- Classes with spells in the SRD, and their usual spellcasting ability
Spells.CLASSES = {
    { key = "bard", name = "Bard", ability = "cha" },
    { key = "cleric", name = "Cleric", ability = "wis" },
    { key = "druid", name = "Druid", ability = "wis" },
    { key = "paladin", name = "Paladin", ability = "cha" },
    { key = "ranger", name = "Ranger", ability = "wis" },
    { key = "sorcerer", name = "Sorcerer", ability = "cha" },
    { key = "warlock", name = "Warlock", ability = "cha" },
    { key = "wizard", name = "Wizard", ability = "int" },
}
Spells.CLASS_BY_KEY = {}
for _, cl in ipairs(Spells.CLASSES) do Spells.CLASS_BY_KEY[cl.key] = cl end

function Spells.className(key)
    local cl = Spells.CLASS_BY_KEY[key]
    return cl and T(cl.name) or key
end

--- Class key for a free text such as "Wizard", "mago" or "Chierico 5".
function Spells.classFromText(text)
    text = util.trim(text or ""):lower()
    if text == "" then return nil end
    for _, cl in ipairs(Spells.CLASSES) do
        for _, name in ipairs({ cl.name:lower(), T(cl.name):lower() }) do
            if text == name or text:find("^" .. name .. "%f[^%w]") then
                return cl.key
            end
        end
    end
end

local loaded_key, loaded

--- Language of the spell texts: the plugin's, when there is a list for it.
function Spells.language(edition)
    local code = I18n.code()
    if lfs.attributes(spells_dir .. edition .. "_" .. code .. ".lua", "mode") == "file" then
        return code
    end
    return "en"
end

--- The list for an edition, { list = { spell, ... }, by_id = { [id] = spell } },
-- or nil if it can't be read.
function Spells.load(edition)
    local key = edition .. "_" .. Spells.language(edition)
    if loaded_key ~= key then
        loaded_key, loaded = key, nil
        collectgarbage()
        local ok, list = pcall(dofile, spells_dir .. key .. ".lua")
        if ok and type(list) == "table" then
            local by_id = {}
            for _, s in ipairs(list) do by_id[s.id] = s end
            loaded = { list = list, by_id = by_id }
        end
    end
    return loaded
end

function Spells.get(edition, id)
    local db = id and Spells.load(edition)
    return db and db.by_id[id]
end

--- Spells of one level, for one class (or all of them if class is nil).
function Spells.list(edition, level, class)
    local db = Spells.load(edition)
    local out = {}
    if not db then return out end
    for _, s in ipairs(db.list) do
        if s.level == level then
            local ok = class == nil
            if not ok then
                for _, c in ipairs(s.classes) do
                    if c == class then ok = true break end
                end
            end
            if ok then table.insert(out, s) end
        end
    end
    return out
end

--- Number of spells per level (index 0 to 9) for a class.
function Spells.counts(edition, class)
    local counts = {}
    for lvl = 0, 9 do counts[lvl] = #Spells.list(edition, lvl, class) end
    return counts
end

-- Text to HTML ----------------------------------------------------------------

local function escape(s)
    return (s:gsub("&", "&amp;"):gsub("<", "&lt;"):gsub(">", "&gt;"))
end

local function inline(s)
    s = escape(s)
    s = s:gsub("%*%*(.-)%*%*", "<b>%1</b>")
    s = s:gsub("%*(.-)%*", "<i>%1</i>")
    return s
end

--- The spell text format (see tools/srd/build.py) as HTML: paragraphs,
-- "## " sub-headings, tables with " | " between cells, **bold**, *italic*.
function Spells.textToHtml(text)
    local out = {}
    for block in (text .. "\n\n"):gmatch("(.-)\n\n") do
        if block:find(" | ", 1, true) then
            local rows = {}
            for line in (block .. "\n"):gmatch("(.-)\n") do
                local cells = {}
                for cell in (line .. " | "):gmatch("(.-) | ") do
                    table.insert(cells, "<td>" .. inline(cell) .. "</td>")
                end
                table.insert(rows, "<tr>" .. table.concat(cells) .. "</tr>")
            end
            table.insert(out, "<table>" .. table.concat(rows) .. "</table>")
        elseif block:sub(1, 3) == "## " then
            table.insert(out, "<h4>" .. inline(block:sub(4)) .. "</h4>")
        elseif block ~= "" then
            table.insert(out, "<p>" .. inline(block) .. "</p>")
        end
    end
    return table.concat(out)
end

--- "Evocation, level 3" / "Evocation cantrip", then the classes.
function Spells.subtitle(s)
    local kind
    if s.level == 0 then
        kind = string.format(T("%s cantrip"), s.school)
    else
        kind = string.format(T("%s, level %d"), s.school, s.level)
    end
    local classes = {}
    for _, c in ipairs(s.classes) do table.insert(classes, Spells.className(c)) end
    if #classes > 0 then kind = kind .. " (" .. table.concat(classes, ", ") .. ")" end
    return kind
end

--- Full description of a spell as HTML.
function Spells.html(s)
    local function field(label, value)
        if not value or value == "" then return "" end
        return "<div><b>" .. escape(label) .. ":</b> " .. escape(value) .. "</div>"
    end
    local comp = s.comp or ""
    if s.material and s.material ~= "" then comp = comp .. " (" .. s.material .. ")" end
    return "<p><i>" .. escape(Spells.subtitle(s)) .. "</i></p>"
        .. field(T("Casting time"), (s.time or "") .. (s.ritual and (" · " .. T("Ritual")) or ""))
        .. field(T("Range"), s.range)
        .. field(T("Components"), comp)
        .. field(T("Duration"), s.duration)
        .. Spells.textToHtml(s.text or "")
end

--- Attribution shown under the list, as the licence asks.
function Spells.source(edition)
    if edition == "2024" then
        return T("Spells from the System Reference Document 5.2.1 by Wizards of the Coast, CC-BY-4.0.")
    end
    return T("Spells from the System Reference Document 5.1 by Wizards of the Coast, CC-BY-4.0.")
end

return Spells
